[tool.poetry]
name = "nanonispy"
version = "1.1.0"
description = "Read Nanonis data files"
authors = ["Yann-Sebastien Tremblay-Johnston <yanns.tremblay@gmail.com>"]
license = "MIT"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"